FROM oven/bun:1-alpine
WORKDIR /app

COPY package.json bun.lockb* ./
COPY packages/server/package.json ./packages/server/
COPY packages/config/package.json ./packages/config/
RUN bun install --frozen-lockfile

COPY packages/server ./packages/server
COPY packages/config ./packages/config

CMD ["bun", "run", "--cwd", "packages/server", "migrate"]
